trigger:
- master

pr:
  - "*"

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage:  'ubuntu-latest'
  steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '3.1.100'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
- job: Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '3.1.100'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        nobuild: true
        versioningScheme: 'off'
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'MyGet'
